version: "3.5"
networks:
  backend:
    driver: overlay
    # driver_opts:
    #   encrypted: "1"
services:
  hub:
    image: selenium/hub:3.12.0-boron
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
      - GRID_NEW_SESSION_WAIT_TIMEOUT=-1
      - GRID_THROW_ON_CAPABILITY_NOT_PRESENT=true
      - GRID_JETTY_MAX_THREADS=-1
      - GRID_CLEAN_UP_CYCLE=5000
      - GRID_BROWSER_TIMEOUT=0
      - GRID_TIMEOUT=0
      - GRID_DEBUG=false
      - GRID_MAX_SESSION=100
      # - JAVA_OPTS=-Xmx1024m
    entrypoint: bash -c 'SE_OPTS="-timeout 86400 -browserTimeout 86400" /opt/bin/entry_point.sh'
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    ports:
      - "${SELENIUM_HUB_PORT}:4444"
    networks:
      - backend
    volumes:
      - /dev/shm:/dev/shm
  chrome:
    image: selenium/node-chrome:3.12.0-boron
    depends_on:
      - hub
    environment:
      # - SCREEN_WIDTH=600
      # - SCREEN_HEIGHT=480
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=${SELENIUM_HUB_PORT}
      - NODE_MAX_INSTANCES=${NODE_MAX_INSTANCES}
      - NODE_MAX_SESSION=${NODE_MAX_SESSION}
      # - JAVA_OPTS=-Xmx250m
      # - LOGSPOUT=ignore
      # - DBUS_SESSION_BUS_ADDRESS=/dev/null
    entrypoint: bash -c 'SE_OPTS="-timeout 86400 -browserTimeout 86400 -host $$HOSTNAME -port 5556" /opt/bin/entry_point.sh'
    ports:
      - "${SELENIUM_NODE_CHROME_PORT}:5556"
      - "9222:9222"
    deploy:
      replicas: ${SELENIUM_NODE_CHROME_REPLICAS}
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.9'
          memory: 450M
        reservations:
          cpus: '0.2'
          memory: 300M
      # placement:
      #   constraints: [node.role != manager]
    networks:
      - backend
    volumes:
      - /dev/shm:/dev/shm
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]
    networks:
      - backend
  portainer:
    image: portainer/portainer:latest
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ra/portainer/data:/data
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - backend
  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "${CADVISOR_PORT}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - backend
